repos:
-   repo: https://github.com/igrr/astyle_py.git
    rev: v0.9.0
    hooks:
    -   id: astyle_py
        args: ['--style=otbs', '--attach-namespaces', '--attach-classes', '--indent=spaces=4', '--convert-tabs', '--align-pointer=name', '--align-reference=name', '--keep-one-line-statements', '--pad-header', '--pad-oper']

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
        files: ^usb/
        types_or: [c, c++]
    -   id: end-of-file-fixer
        files: ^usb/
        types_or: [c, c++]
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        files: ^usb/ # temporary USB only
        types_or: [c, c++]
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character
